"""Remove unique coonstraint from Labour.type

Revision ID: 04b12c67acea
Revises: 8c8a8f26018f
Create Date: 2025-01-03 16:55:00.478525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04b12c67acea'
down_revision = '8c8a8f26018f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('labours', schema=None) as batch_op:
        batch_op.drop_index('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('labours', schema=None) as batch_op:
        batch_op.create_index('type', ['type'], unique=True)

    # ### end Alembic commands ###
