"""Added composite uniqueness constraint for Farmer

Revision ID: 19a86ea5beaa
Revises: 04b12c67acea
Create Date: 2025-01-03 18:10:27.899303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19a86ea5beaa'
down_revision = '04b12c67acea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_index('phone_number')
        batch_op.create_unique_constraint('unique_employee_name_phone_per_farmer', ['name', 'phone_number', 'farmer_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_constraint('unique_employee_name_phone_per_farmer', type_='unique')
        batch_op.create_index('phone_number', ['phone_number'], unique=True)

    # ### end Alembic commands ###
