"""Renamed job_type_id to labour_id for consistency

Revision ID: 47b0e15dbc16
Revises: 19a86ea5beaa
Create Date: 2025-01-04 11:22:57.198292

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '47b0e15dbc16'
down_revision = '19a86ea5beaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('labour_id', sa.String(length=128), nullable=False))
        batch_op.drop_constraint('employees_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'labours', ['labour_id'], ['id'])
        batch_op.drop_column('job_type_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_type_id', mysql.VARCHAR(length=128), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('employees_ibfk_1', 'labours', ['job_type_id'], ['id'])
        batch_op.drop_column('labour_id')

    # ### end Alembic commands ###
