"""added composite uniqueness for farmer, labour

Revision ID: 8c8a8f26018f
Revises: fb17ffa0d4eb
Create Date: 2025-01-02 19:02:24.455879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c8a8f26018f'
down_revision = 'fb17ffa0d4eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('labours', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_labour_type_per_farmer', ['type', 'farmer_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('labours', schema=None) as batch_op:
        batch_op.drop_constraint('unique_labour_type_per_farmer', type_='unique')

    # ### end Alembic commands ###
