"""Update quantity field to integer

Revision ID: 8d02b8c0b799
Revises: 88830059e827
Create Date: 2024-09-17 14:09:27.458143

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8d02b8c0b799'
down_revision = '88830059e827'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=mysql.FLOAT(),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=sa.String(length=255),
               type_=mysql.FLOAT(),
               existing_nullable=False)

    # ### end Alembic commands ###
