"""modified inventory updated_at to added_at

Revision ID: b113f5530968
Revises: 8d02b8c0b799
Create Date: 2024-09-17 15:47:48.339384

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b113f5530968'
down_revision = '8d02b8c0b799'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_added', sa.DateTime(), nullable=True))
        batch_op.drop_column('date_updated')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_updated', mysql.DATETIME(), nullable=True))
        batch_op.drop_column('date_added')

    # ### end Alembic commands ###
