"""Added rltnshp between Farmer and Labour

Revision ID: fb17ffa0d4eb
Revises: d5947fbe2e68
Create Date: 2025-01-02 17:22:13.162104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb17ffa0d4eb'
down_revision = 'd5947fbe2e68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('labours', schema=None) as batch_op:
        batch_op.add_column(sa.Column('farmer_id', sa.String(length=128), nullable=False))
        batch_op.create_foreign_key(None, 'farmers', ['farmer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('labours', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('farmer_id')

    # ### end Alembic commands ###
